# Generated by Django 6.0.1 on 2026-01-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_sku',
            field=models.CharField(default='LEGACY-SKU', max_length=50),
            preserve_default=False,
        ),
    ]
